[package]
name = "cobbledb"
version = "0.1.0"
authors = ["jyizheng <jyizheng@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
integer-encoding = "1.0"